--Task 1
SELECT PDB_NAME, STATUS FROM CDB_PDBS;
--SELECT * FROM CDB_PDBS;

--Task 2
SELECT INSTANCE_NAME, HOST_NAME FROM V$INSTANCE;

--Task 3
SELECT COMP_ID, COMP_NAME, VERSION, STATUS FROM DBA_REGISTRY;

--Task 4
CREATE PLUGGABLE DATABASE SNE_PDB ADMIN USER pbd_admin IDENTIFIED BY sne1234
ROLES = (DBA) FILE_NAME_CONVERT =('/opt/oracle/oradata/FREE/pdbseed/', '/opt/oracle/oradata/FREE/pdbseed/SNE_PDB/');

ALTER PLUGGABLE DATABASE SNE_PDB OPEN;

--Task 5
SELECT * FROM dba_pdbs where PDB_NAME = 'SNE_PDB';

--Task 6
--PDBCONECTION
--Drop TableSpace TS1_PDB_SNE including CONTENTS AND DATAFILES
CREATE TABLESPACE TS1_PDB_SNE
DATAFILE 'TS1_PDB_SNE.dbf'
SIZE 7M
AUTOEXTEND ON
NEXT 3M
MAXSIZE 30M;

--Drop TableSpace TS1_PDB_SNE_TEMP including CONTENTS AND DATAFILES
CREATE TEMPORARY TABLESPACE TS1_PDB_SNE_TEMP
TEMPFILE 'TS2_PDB_SNE_TEMP.dbf'
SIZE 5M
AUTOEXTEND ON
NEXT 3M
MAXSIZE 30M;

--DROP ROLE RL_PDB_SNECORE;
ALTER SESSION SET "_ORACLE_SCRIPT"=true;
CREATE ROLE RL_PDB_SNECORE;

select * from DBA_ROLE_PRIVS where GRANTED_ROLE = 'RL_PDB_SNECORE';
REVOKE RL_PDB_SNECORE From U1_SNE_PDB;

GRANT CONNECT, CREATE SESSION, CREATE ANY TABLE, DROP ANY TABLE, CREATE ANY VIEW,
DROP ANY VIEW, CREATE ANY PROCEDURE, DROP ANY PROCEDURE TO RL_PDB_SNECORE;

--DROP PROFILE PF_PDB_SNECORE;
CREATE PROFILE PF_PDB_SNECORE LIMIT
PASSWORD_LIFE_TIME 365
SESSIONS_PER_USER 5
FAILED_LOGIN_ATTEMPTS 5
PASSWORD_LOCK_TIME 1
PASSWORD_REUSE_TIME 10
PASSWORD_GRACE_TIME DEFAULT
CONNECT_TIME 180
IDLE_TIME 45;

--DROP USER U1_SNE_PDB CASCADE;
CREATE USER U1_SNE_PDB IDENTIFIED BY pdb123
DEFAULT TABLESPACE TS1_PDB_SNE QUOTA UNLIMITED ON TS1_PDB_SNE
TEMPORARY TABLESPACE TS1_PDB_SNE_TEMP
PROFILE PF_PDB_SNECORE
ACCOUNT UNLOCK
PASSWORD EXPIRE;

GRANT RL_PDB_SNECORE TO U1_SNE_PDB;

--Task 7
--U1_SNE_PDB
--DROP TABLE SNE_TABLE;
CREATE TABLE SNE_TABLE (x NUMBER(2), y VARCHAR2(20));

INSERT ALL
    INTO SNE_TABLE VALUES(1, 'HELLO')
    INTO SNE_TABLE VALUES(2, 'HELLO2')
    SELECT * FROM dual;
    
COMMIT;
    
SELECT * FROM SNE_TABLE;

--Task 8
--SYS
SELECT * FROM DBA_ROLES ;
SELECT * FROM DBA_PROFILES;
SELECT * FROM ALL_USERS;

SELECT * FROM DBA_DATA_FILES;
SELECT * FROM DBA_TEMP_FILES;
SELECT grantee, privilege FROM dba_sys_privs;

--Task 9
--CDB
CREATE USER C##SNE IDENTIFIED BY sne123;
GRANT CONNECT, CREATE SESSION, ALTER SESSION, CREATE ANY TABLE,
DROP ANY TABLE TO C##SNE CONTAINER = ALL;
-- PDB
GRANT CREATE SESSION TO C##SNE;

--Task 10
ALTER PLUGGABLE DATABASE SNE_PDB Close IMMEDIATE;
DROP PLUGGABLE DATABASE SNE_PDB INCLUDING DATAFILES;
DROP USER C##SNE; 

drop user SNECORE CASCADE;
alter user SNECORE IDENTIFIED By sne1234;

