SET SERVEROUTPUT ON;
--ALTER DATABASE DATAFILE '/opt/oracle/product/23ai/dbhomeFree/dbs/TS1_PDB_SNE.dbf' RESIZE 200M;

-- GRANTS
GRANT CREATE TABLESPACE TO U1_SNE_PDB;
GRANT ALTER DATABASE TO U1_SNE_PDB;
GRANT ALTER USER TO U1_SNE_PDB;

-- TABLESPACE
CREATE TABLESPACE TS_HASH1 DATAFILE 'ts_hash1.dbf' SIZE 10M;
CREATE TABLESPACE TS_HASH2 DATAFILE 'ts_hash2.dbf' SIZE 10M;
CREATE TABLESPACE TS_HASH3 DATAFILE 'ts_hash3.dbf' SIZE 10M;
CREATE TABLESPACE TS_HASH4 DATAFILE 'ts_hash4.dbf' SIZE 10M;

-- DATABASES
ALTER DATABASE DATAFILE 'ts_hash1.dbf' RESIZE 50M;
ALTER DATABASE DATAFILE 'ts_hash2.dbf' RESIZE 50M;
ALTER DATABASE DATAFILE 'ts_hash3.dbf' RESIZE 50M;
ALTER DATABASE DATAFILE 'ts_hash4.dbf' RESIZE 50M;

-- USERS
ALTER USER U1_SNE_PDB QUOTA 30M ON TS_HASH1;
ALTER USER U1_SNE_PDB QUOTA 30M ON TS_HASH2;
ALTER USER U1_SNE_PDB QUOTA 30M ON TS_HASH3;
ALTER USER U1_SNE_PDB QUOTA 30M ON TS_HASH4;

DROP TABLE T_RANGE;
DROP TABLE T_INTERVAL;
DROP TABLE T_HASH;
DROP TABLE T_LIST;
DROP TABLE EXCHANGE_TABLE_TEST;

-- Task 1 
CREATE TABLE T_RANGE (
    ID NUMBER,
    Name VARCHAR2(50)
)
PARTITION BY RANGE (ID) (
    PARTITION P1 VALUES LESS THAN (100),
    PARTITION P2 VALUES LESS THAN (200),
    PARTITION P3 VALUES LESS THAN (MAXVALUE)
);

-- Task 2 
CREATE TABLE T_INTERVAL (
    EventID NUMBER,
    EventDate DATE,
    Description VARCHAR2(100)
)
PARTITION BY RANGE (EventDate)
    INTERVAL (NUMTOYMINTERVAL(1, 'MONTH')) (
    PARTITION P0 VALUES LESS THAN (TO_DATE('2010-01-01', 'YYYY-MM-DD')),
    PARTITION P1 VALUES LESS THAN (TO_DATE('2024-01-01', 'YYYY-MM-DD'))

);

-- Task 3 
CREATE TABLE T_HASH (
    UserID NUMBER,
    Username VARCHAR2(50)
)
PARTITION BY HASH (Username) (
    PARTITION t1 TABLESPACE TS_HASH1,
    PARTITION t2 TABLESPACE TS_HASH2,
    PARTITION t3 TABLESPACE TS_HASH3,
    PARTITION t4 TABLESPACE TS_HASH4
);

-- Task 4 
CREATE TABLE T_LIST (
    RegionCode CHAR(2),
    RegionName VARCHAR2(50)
)
PARTITION BY LIST (RegionCode) (
    PARTITION North VALUES ('N'),
    PARTITION South VALUES ('S'),
    PARTITION East VALUES ('E'),
    PARTITION West VALUES ('W')
);

-- Task 5 
INSERT INTO T_RANGE VALUES (50,  'Test_1');
INSERT INTO T_RANGE VALUES (150, 'Test_2');
INSERT INTO T_RANGE VALUES (250, 'Test_3');

SELECT * FROM T_RANGE PARTITION (P1); 
SELECT * FROM T_RANGE PARTITION (P2); 
SELECT * FROM T_RANGE PARTITION (P3); 

INSERT INTO T_INTERVAL VALUES (1, TO_DATE('2009-01-15', 'YYYY-MM-DD'), 'Event1');
INSERT INTO T_INTERVAL VALUES (2, TO_DATE('2025-01-01', 'YYYY-MM-DD'), 'Event2');

SELECT * FROM T_INTERVAL PARTITION (P0);
SELECT * FROM T_INTERVAL PARTITION (P1);

INSERT INTO T_HASH VALUES (1, 'Test_1');
INSERT INTO T_HASH VALUES (2, 'Test_2');
INSERT INTO T_HASH VALUES (3, 'Test_3');
INSERT INTO T_HASH VALUES (4, 'Test_4');

SELECT * FROM T_HASH PARTITION (t1);
SELECT * FROM T_HASH PARTITION (t2); 
SELECT * FROM T_HASH PARTITION (t3);
SELECT * FROM T_HASH PARTITION (t4); 

INSERT INTO T_LIST VALUES ('N', 'NorthRegion');
INSERT INTO T_LIST VALUES ('S', 'SouthRegion');
INSERT INTO T_LIST VALUES ('E', 'EastRegion');
INSERT INTO T_LIST VALUES ('W', 'WestRegion');

SELECT * FROM T_LIST PARTITION (North);
SELECT * FROM T_LIST PARTITION (South);
SELECT * FROM T_LIST PARTITION (East);
SELECT * FROM T_LIST PARTITION (West);


-- Task 6 
--1
alter table T_RANGE ENABLE row MOVEMENT;
UPDATE T_RANGE SET ID = 125 WHERE Name = 'Test_1'; -- P1 -> P2

SELECT * FROM T_RANGE PARTITION (P1);
SELECT * FROM T_RANGE PARTITION (P2);

--2
alter table T_INTERVAL ENABLE row MOVEMENT;
UPDATE T_INTERVAL SET EventDate = TO_DATE('2008-01-01', 'YYYY-MM-DD') WHERE EventID = 2;

SELECT * FROM T_INTERVAL PARTITION (P0);
SELECT * FROM T_INTERVAL PARTITION (P1);

--3
alter table T_HASH ENABLE row MOVEMENT;
UPDATE T_HASH SET Username = '5_test' WHERE UserID = 1;
SELECT * FROM T_HASH PARTITION(t1);
SELECT * FROM T_HASH PARTITION(t2);
SELECT * FROM T_HASH PARTITION(t3);
SELECT * FROM T_HASH PARTITION(t4);

--4
alter table T_LIST ENABLE row MOVEMENT;
UPDATE T_LIST SET RegionCode = 'E' WHERE RegionName = 'NorthRegion'; -- North -> East

SELECT * FROM T_LIST PARTITION (North);
SELECT * FROM T_LIST PARTITION (East);

-- Task 7 
ALTER TABLE T_RANGE
MERGE PARTITIONS P1, P2 INTO PARTITION P1_2;

SELECT * FROM T_RANGE PARTITION (P1_2);

-- Task 8 
ALTER TABLE T_RANGE
SPLIT PARTITION P1_2 AT (130)
INTO (PARTITION P0_1, PARTITION P0_2);

SELECT * FROM T_RANGE PARTITION (P0_1);
SELECT * FROM T_RANGE PARTITION (P0_2);

-- Task 9 
CREATE TABLE EXCHANGE_TABLE_TEST (
    ID NUMBER,
    Name VARCHAR2(50)
);

INSERT INTO EXCHANGE_TABLE_TEST VALUES (30,  'Test_EXCHANGE_1');

ALTER TABLE T_RANGE EXCHANGE PARTITION P0_1 WITH TABLE EXCHANGE_TABLE_TEST;


SELECT * FROM EXCHANGE_TABLE_TEST; 
SELECT * FROM T_RANGE PARTITION (P0_1);
