ALTER SESSION SET nls_date_format = 'DD-MM-YYYY';
SET SERVEROUTPUT ON;
-- Task 1

ALTER TABLE TEACHER
    ADD BIRTHDAY date;
ALTER TABLE TEACHER
    ADD SALARY number;

UPDATE TEACHER
SET BIRTHDAY = '12-02-1959'
WHERE TEACHER = 'СМЛВ';
UPDATE TEACHER
SET BIRTHDAY = '30-01-1987'
WHERE TEACHER = 'АКНВЧ';
UPDATE TEACHER
SET BIRTHDAY = '19-04-1991'
WHERE TEACHER = 'КЛСНВ';
UPDATE TEACHER
SET BIRTHDAY = '16-04-1964'
WHERE TEACHER = 'ГРМН';
UPDATE TEACHER
SET BIRTHDAY = '19-11-1988'
WHERE TEACHER = 'ЛЩНК';
UPDATE TEACHER
SET BIRTHDAY = '05-10-1966'
WHERE TEACHER = 'БРКВЧ';
UPDATE TEACHER
SET BIRTHDAY = '10-08-1976'
WHERE TEACHER = 'ДДК';
UPDATE TEACHER
SET BIRTHDAY = '11-09-1989'
WHERE TEACHER = 'КБЛ';
UPDATE TEACHER
SET BIRTHDAY = '24-12-1983'
WHERE TEACHER = 'УРБ';
UPDATE TEACHER
SET BIRTHDAY = '03-06-1990'
WHERE TEACHER = 'РМНК';
UPDATE TEACHER
SET BIRTHDAY = '10-05-1970'
WHERE TEACHER = 'ПСТВЛВ';
UPDATE TEACHER
SET BIRTHDAY = '26-10-1999'
WHERE TEACHER = '?';
UPDATE TEACHER
SET BIRTHDAY = '30-07-1984'
WHERE TEACHER = 'ГРН';
UPDATE TEACHER
SET BIRTHDAY = '11-03-1975'
WHERE TEACHER = 'ЖЛК';
UPDATE TEACHER
SET BIRTHDAY = '12-07-1969'
WHERE TEACHER = 'БРТШВЧ';
UPDATE TEACHER
SET BIRTHDAY = '26-02-1983'
WHERE TEACHER = 'ЮДНКВ';
UPDATE TEACHER
SET BIRTHDAY = '13-12-1991'
WHERE TEACHER = 'БРНВСК';
UPDATE TEACHER
SET BIRTHDAY = '20-01-1968'
WHERE TEACHER = 'НВРВ';
UPDATE TEACHER
SET BIRTHDAY = '21-12-1969'
WHERE TEACHER = 'РВКЧ';
UPDATE TEACHER
SET BIRTHDAY = '28-01-1975'
WHERE TEACHER = 'ДМДК';
UPDATE TEACHER
SET BIRTHDAY = '10-07-1983'
WHERE TEACHER = 'МШКВСК';
UPDATE TEACHER
SET BIRTHDAY = '08-10-1988'
WHERE TEACHER = 'ЛБХ';
UPDATE TEACHER
SET BIRTHDAY = '30-07-1984'
WHERE TEACHER = 'ЗВГЦВ';
UPDATE TEACHER
SET BIRTHDAY = '16-04-1964'
WHERE TEACHER = 'БЗБРДВ';
UPDATE TEACHER
SET BIRTHDAY = '12-05-1985'
WHERE TEACHER = 'ПРКПЧК';
UPDATE TEACHER
SET BIRTHDAY = '20-10-1980'
WHERE TEACHER = 'НСКВЦ';
UPDATE TEACHER
SET BIRTHDAY = '21-08-1990'
WHERE TEACHER = 'МХВ';
UPDATE TEACHER
SET BIRTHDAY = '13-08-1966'
WHERE TEACHER = 'ЕЩНК';
UPDATE TEACHER
SET BIRTHDAY = '11-11-1978'
WHERE TEACHER = 'ЖРСК';

UPDATE TEACHER
SET SALARY = 1030
WHERE TEACHER = 'СМЛВ';
UPDATE TEACHER
SET SALARY = 1030
WHERE TEACHER = 'АКНВЧ';
UPDATE TEACHER
SET SALARY = 980
WHERE TEACHER = 'КЛСНВ';
UPDATE TEACHER
SET SALARY = 1050
WHERE TEACHER = 'ГРМН';
UPDATE TEACHER
SET SALARY = 590
WHERE TEACHER = 'ЛЩНК';
UPDATE TEACHER
SET SALARY = 870
WHERE TEACHER = 'БРКВЧ';
UPDATE TEACHER
SET SALARY = 815
WHERE TEACHER = 'ДДК';
UPDATE TEACHER
SET SALARY = 995
WHERE TEACHER = 'КБЛ';
UPDATE TEACHER
SET SALARY = 1460
WHERE TEACHER = 'УРБ';
UPDATE TEACHER
SET SALARY = 1120
WHERE TEACHER = 'РМНК';
UPDATE TEACHER
SET SALARY = 1250
WHERE TEACHER = 'ПСТВЛВ';
UPDATE TEACHER
SET SALARY = 333
WHERE TEACHER = '?';
UPDATE TEACHER
SET SALARY = 1520
WHERE TEACHER = 'ГРН';
UPDATE TEACHER
SET SALARY = 1430
WHERE TEACHER = 'ЖЛК';
UPDATE TEACHER
SET SALARY = 900
WHERE TEACHER = 'БРТШВЧ';
UPDATE TEACHER
SET SALARY = 875
WHERE TEACHER = 'ЮДНКВ';
UPDATE TEACHER
SET SALARY = 970
WHERE TEACHER = 'БРНВСК';
UPDATE TEACHER
SET SALARY = 780
WHERE TEACHER = 'НВРВ';
UPDATE TEACHER
SET SALARY = 1150
WHERE TEACHER = 'РВКЧ';
UPDATE TEACHER
SET SALARY = 805
WHERE TEACHER = 'ДМДК';
UPDATE TEACHER
SET SALARY = 905
WHERE TEACHER = 'МШКВСК';
UPDATE TEACHER
SET SALARY = 1200
WHERE TEACHER = 'ЛБХ';
UPDATE TEACHER
SET SALARY = 1500
WHERE TEACHER = 'ЗВГЦВ';
UPDATE TEACHER
SET SALARY = 905
WHERE TEACHER = 'БЗБРДВ';
UPDATE TEACHER
SET SALARY = 715
WHERE TEACHER = 'ПРКПЧК';
UPDATE TEACHER
SET SALARY = 880
WHERE TEACHER = 'НСКВЦ';
UPDATE TEACHER
SET SALARY = 735
WHERE TEACHER = 'МХВ';
UPDATE TEACHER
SET SALARY = 595
WHERE TEACHER = 'ЕЩНК';
UPDATE TEACHER
SET SALARY = 850
WHERE TEACHER = 'ЖРСК';

-- Task 2
SELECT CONCAT(
         SUBSTR(TEACHER_NAME, 1, INSTR(TEACHER_NAME, ' ')), 
         SUBSTR(TEACHER_NAME, INSTR(TEACHER_NAME, ' ') + 1, 1), '.',
         SUBSTR(TEACHER_NAME, INSTR(TEACHER_NAME, ' ', 1, 2) + 1, 1), '.'
       ) AS TEACHER
FROM TEACHER;

-- Task 3
SELECT *
FROM teacher
WHERE TO_CHAR(birthday, 'd') = 2;

-- Task 4
--drop view next_month

CREATE OR REPLACE VIEW next_month AS
    SELECT tch.TEACHER_NAME, tch.birthday
    FROM TEACHER tch
    WHERE TO_CHAR(tch.birthday, 'MM') = TO_CHAR(ADD_MONTHS(SYSDATE, 1), 'MM');

SELECT * FROM next_month;

-- Task 5
--drop view number_months
create or replace view number_months as
    select to_char(birthday, 'Month') Месяц, count(*) Количество
    from teacher
    group by to_char(birthday, 'Month')
    having count(*) >= 1
    order by Количество desc;

select * from number_months;

-- Task 6
DECLARE
    CURSOR HAPPY_DATE IS
        SELECT
            TEACHER_NAME, BIRTHDAY
        FROM TEACHER
        WHERE MOD(EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM BIRTHDAY + 1), 10) = 0;
BEGIN
    FOR TEACH IN HAPPY_DATE 
    LOOP
        DBMS_OUTPUT.PUT_LINE(TEACH.TEACHER_NAME || ' ' || TEACH.BIRTHDAY);    
    END LOOP;
END;

-- Task 7
DECLARE
    CURSOR TEACH_AVG_SALARY IS
        SELECT 
            PULPIT,
            FLOOR(AVG(SALARY)) AS AVG_SALARY
        FROM TEACHER
        GROUP BY PULPIT;
    CURSOR PULPIT_AVG_SALARY IS
        SELECT 
            FACULTY,
            FLOOR(AVG(SALARY)) AS AVG_SALARY
        FROM TEACHER
            JOIN PULPIT p on TEACHER.PULPIT = p.PULPIT
        GROUP BY FACULTY;
    CURSOR FACULTY_AVG_SALARY IS
        SELECT AVG(SALARY) AS AVG_SALARY
        FROM TEACHER;
BEGIN
    DBMS_OUTPUT.PUT_LINE('<==- По кафедрам -==>');
    FOR ELEM IN TEACH_AVG_SALARY
    LOOP
          DBMS_OUTPUT.PUT_LINE(ELEM.PULPIT || ' ' || ELEM.AVG_SALARY); 
    END LOOP;

    DBMS_OUTPUT.PUT_LINE('<==- По факультетам -==>');
    FOR ELEM IN PULPIT_AVG_SALARY
    LOOP
          DBMS_OUTPUT.PUT_LINE(ELEM.FACULTY || ' ' || ELEM.AVG_SALARY); 
    END LOOP;

    DBMS_OUTPUT.PUT_LINE('<==- По всем факультетам -==>');
    FOR ELEM IN FACULTY_AVG_SALARY
    LOOP
          DBMS_OUTPUT.PUT_LINE(ELEM.AVG_SALARY); 
    END LOOP;
END;

-- Task 8
DECLARE
    TYPE innerType is RECORD (
        typeId NUMBER,
        typeName VARCHAR2(33)
    );
    TYPE outerType is RECORD (
        typeId NUMBER,
        typeName VARCHAR2(33),
        inner innerType
    );

    innerTest innerType;
    outerTest outerType;
BEGIN
    innerTest := innerType(0, 'Goshavich');
    outerTest := outerType(1, 'Georgy', innerTest);

    DBMS_OUTPUT.PUT_LINE('Outer Id: ' || outerTest.typeId || ';');
    DBMS_OUTPUT.PUT_LINE('Outer Name: ' || outerTest.typeName || ';');
    DBMS_OUTPUT.PUT_LINE('Childs Id: ' || outerTest.inner.typeId || ';');
    DBMS_OUTPUT.PUT_LINE('Childs Name: ' || outerTest.inner.typeName || ';');
    DBMS_OUTPUT.PUT_LINE('Id: ' || outerTest.inner.typeId || outerTest.typeId || '; Full name: ' || outerTest.inner.typeName  || ' ' || outerTest.typeName || ';');
END;